---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  environments_path: test/fixtures/environments
  nodes_path: test/fixtures/nodes
  roles_path: test/fixtures/roles

platforms:
  - name: ubuntu-16.04
    driver_config:
        network:
            - ["forwarded_port", {guest: 443, host: 4433}]
suites:
  - name: default
    run_list:
      - recipe[ubiquiti_server::default]
    attributes:
